# Site settings
title: Gotten
tagline: Generic MDE framework fOr meTamorphic TEstiNg
description: >
  Generic MDE framework fOr meTamorphic TEstiNg
baseurl: ""
url: "https://g0tten.github.io"
permalink: /:year/:month/:day/:title
repository: g0tten/gotten
paginate: 5

# Project links
github_profile: "https://github.com/g0tten"
user: "Gotten project"
user_email: "pablo.gomeza@uam.es"
contact_url: "https://gomezabajo.github.io"
update_site_url: "https://g0tten.github.io/gotten/update-site"
standalone_url: "https://www.dropbox.com/scl/fi/vkur2m59l42bg41mbjb9b/eclipse.zip?rlkey=714vya0es6bal55qp2rwqyz4c&dl=0"
standalone_url_ubuntu: "https://www.dropbox.com/scl/fi/hjbgcbmf0qomb16jyc6gl/eclipse.zip?rlkey=67fnqcl7whv0lrkhd0x370yh2&dl=0"

# Analytics / comments
google_tracking_id: "G-JKMPYJFGYJ"
google_site_verification: ""
disqus_shortname: "gomezabajo"

categories: default

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
future: true
